### PR TITLE
to_str() now returns string representation of arrays and objects

### PR DESCRIPTION
**Pull request by tripzero**
Signed-off-by: Kevron Rees <kevron.m.rees@intel.com>

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

serialize() method already exists for converting objects to JSON.

Would you mind explaining why you would want to modify to_str()?

**Comment by tripzero** [comment]
That's a good point.  It seems like to_str() is actually redundant because serialize does virtually the same thing.  I really don't see a point to just returning "array" or "object" when calling to_str().  I'm probably misunderstanding why it's needed.

**Comment by kazuho** [comment]
`.to_str()` existed well before `.serialize()` was added.  In the early days, `.to_str()` was as the one and only function good for printing debugging information.  It is true that it has become redundant, but is kept as is for backward compatibility.

If you have any reason to use the proposed version of `.to_str()` instead of `.serialize()` please explain why.  If not, it would be great if you could close the PR.

**Comment by tripzero** [comment]
This can be closed.

**Comment by kazuho** [comment]
Thanks.  Closing the issue.

**Pull request closed without merging**
