### PR TITLE
Replace serialize_str handwritten for_each loop with std::for_each,

### PR DESCRIPTION
**Pull request by BillyONeal**
…improving performance up to 2x on MSVC++ in debug mode /Od /RTC1.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Sorry, I did not realize only C++03 was OK. Will rework.

**Comment by AndiDog** [comment]
Also, don't benchmark in debug mode.

**Comment by BillyONeal** [comment]
@AndiDog While of course release mode perf is more important than debug mode perf, this particular function contributes to 200x performance differences between debug builds and release builds; slow enough that debug builds are effectively useless.

**Comment by mattn** [comment]
I tried this on VS2012 and gcc on mingw64.

https://gist.github.com/mattn/3816ce0481d6a71d1771e84bebfcfc07

## mingw64

before patching: g++ foo.cxx
4318

after patching: g++ -std=c++11 foo.cxx
4292

## MSVC (without debug option)

before patching (MSVC)
14007

after patching (MSVC)
13222

## MSVC (with debug option)

before patching (MSVC & /Od /RTC1)
16254

after patching (MSVC & /Od /RTC1)
16162

Well, seems nothing improved. And this change uses lambda. So require C++11.

**Comment by mattn** [comment]
Ah, sorry. My benchmark include reading file. Will update

**Comment by BillyONeal** [comment]
@mattn Regarding the lambda, that's why I closed this PR and made a new PR that doesn't use a C++11 lambda when the CI build rejected this change.

I don't have permission from the customer who reported the bug to share their benchmark (it was reported as a debug mode performance problem against the STL); but in this scenario it made one of their unit test runs go from 0.05s _ITERATOR_DEBUG_LEVEL==0 /O2 to 10s /Od /RTC1. I made some changes to basic_string which cut that debug penalty in half (down to 5s), and this for_each change cut that in half again (down to around 2-2.5 seconds).

If you folks don't want to take the change that's completely fine; I'm mostly just trying to contribute where I can since I had to spend a bunch of time looking at this in the profiler.

**Comment by BillyONeal** [comment]
@mattn That benchmark actually looks pretty close to the customer's. Maybe we were testing different switches or a different platform? It could be different machines but the issue repros on the customers machine and both machines on which I tried it.

```
C:\Users\bion\Desktop\picojson-perf>.\build_O2.cmd && .\x64\Debug\PICOJSON-PERF.EXE

C:\Users\bion\Desktop\picojson-perf>cl /c /ZI /nologo /W3 /WX- /O2 /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"X64\DEBUG\\" /Fd"X64\DEBUG\VC140.PDB" /Gd /TP C:\USERS\BION\DESKTOP\PICOJSON-PERF\TEST.CPP
TEST.CPP

C:\Users\bion\Desktop\picojson-perf>link /OUT:"C:\USERS\BION\DESKTOP\PICOJSON-PERF\X64\DEBUG\PICOJSON-PERF.EXE" /INCREMENTAL /NOLOGO KERNEL32.LIB USER32.LIB GDI32.LIB WINSPOOL.LIB COMDLG32.LIB ADVAPI32.LIB SHELL32.LIB OLE32.LIB OLEAUT32.LIB UUID.LIB ODBC32.LIB ODBCCP32.LIB /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /PDB:"C:\USERS\BION\DESKTOP\PICOJSON-PERF\X64\DEBUG\PICOJSON-PERF.PDB" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\USERS\BION\DESKTOP\PICOJSON-PERF\X64\DEBUG\PICOJSON-PERF.LIB" /MACHINE:X64 X64\DEBUG\TEST.OBJ
Reading CSV ... done. Serializing ... 8271 elements - 0.038 s

C:\Users\bion\Desktop\picojson-perf>.\build_RTC1.cmd && .\x64\Debug\PICOJSON-PERF.EXE

C:\Users\bion\Desktop\picojson-perf>cl /c /ZI /nologo /W3 /WX- /Od /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"X64\DEBUG\\" /Fd"X64\DEBUG\VC140.PDB" /Gd /TP C:\USERS\BION\DESKTOP\PICOJSON-PERF\TEST.CPP
TEST.CPP

C:\Users\bion\Desktop\picojson-perf>link /OUT:"C:\USERS\BION\DESKTOP\PICOJSON-PERF\X64\DEBUG\PICOJSON-PERF.EXE" /INCREMENTAL /NOLOGO KERNEL32.LIB USER32.LIB GDI32.LIB WINSPOOL.LIB COMDLG32.LIB ADVAPI32.LIB SHELL32.LIB OLE32.LIB OLEAUT32.LIB UUID.LIB ODBC32.LIB ODBCCP32.LIB /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /PDB:"C:\USERS\BION\DESKTOP\PICOJSON-PERF\X64\DEBUG\PICOJSON-PERF.PDB" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\USERS\BION\DESKTOP\PICOJSON-PERF\X64\DEBUG\PICOJSON-PERF.LIB" /MACHINE:X64 X64\DEBUG\TEST.OBJ
Reading CSV ... done. Serializing ... 8271 elements - 7.615 s
```

**Pull request closed without merging**
