### PR TITLE
add rvalue reference support

### PR DESCRIPTION
**Pull request by satoren**
+10%-30% performance on parse

### CODE REVIEW

**Comment by satoren** [comment]
thank you for advice

**Comment by satoren** [comment]
14083ms to 9358ms  on Visual Studio 2015

move
nomove

g++
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
clang++
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)

```
+ g++ -O3 -std=c++03 test.cpp -o gcc03rvalue0
+ g++ -O3 -std=c++11 -DPICOJSON_USE_RVALUE_REFERENCE=0 test.cpp -o gcc11rvalue0
+ g++ -O3 -std=c++11 -DPICOJSON_USE_RVALUE_REFERENCE=1 test.cpp -o gcc11rvalue1
+ clang++ -O3 -std=c++03 test.cpp -o clang03rvalue0
+ clang++ -O3 -std=c++11 -DPICOJSON_USE_RVALUE_REFERENCE=0 test.cpp -o clang11rvalue0
+ clang++ -O3 -std=c++11 -DPICOJSON_USE_RVALUE_REFERENCE=1 test.cpp -o clang11rvalue1

+ ./gcc03rvalue0 citylots.json
real	0m12.117s
user	0m11.820s
sys	0m0.284s

+ ./gcc11rvalue0 citylots.json
real	0m12.069s
user	0m11.692s
sys	0m0.372s

+ ./gcc11rvalue1 citylots.json
real	0m11.604s
user	0m11.280s
sys	0m0.316s

+ ./clang03rvalue0 citylots.json
real	0m13.001s
user	0m12.664s
sys	0m0.328s

+ ./clang11rvalue0 citylots.json
real	0m12.851s
user	0m12.476s
sys	0m0.364s

+ ./clang11rvalue1 citylots.json
real	0m12.454s
user	0m12.156s
sys	0m0.288s
```

test data(180MB)
https://raw.githubusercontent.com/zemirco/sf-city-lots-json/master/citylots.json
test code
```C++
#include <fstream>
#include "picojson.h"
int main(int argc, char* argv[])
{
	std::ifstream ifs(argv[1]);
	picojson::value v;
	picojson::parse(v, ifs);
}
```

**Comment by satoren** [comment]
add throw() to move constructor
```
+ g++ -O3 -std=c++03 -DPICOJSON_USE_RVALUE_REFERENCE=0 test.cpp -o gcc03rvalue0
+ g++ -O3 -std=c++11 -DPICOJSON_USE_RVALUE_REFERENCE=0 test.cpp -o gcc11rvalue0
+ g++ -O3 -std=c++11 -DPICOJSON_USE_RVALUE_REFERENCE=1 test.cpp -o gcc11rvalue1
+ clang++ -O3 -std=c++03 -DPICOJSON_USE_RVALUE_REFERENCE=0 test.cpp -o clang03rvalue0
+ clang++ -O3 -std=c++11 -DPICOJSON_USE_RVALUE_REFERENCE=0 test.cpp -o clang11rvalue0
+ clang++ -O3 -std=c++11 -DPICOJSON_USE_RVALUE_REFERENCE=1 test.cpp -o clang11rvalue1

+ ./gcc03rvalue0 citylots.json
real	0m12.513s
user	0m12.176s
sys	0m0.328s

+ ./gcc11rvalue0 citylots.json
real	0m12.373s
user	0m12.024s
sys	0m0.344s

+ ./gcc11rvalue1 citylots.json
real	0m8.398s
user	0m8.044s
sys	0m0.348s

+ ./clang03rvalue0 citylots.json
real	0m13.588s
user	0m13.184s
sys	0m0.356s

+ ./clang11rvalue0 citylots.json
real	0m13.267s
user	0m12.968s
sys	0m0.288s

+ ./clang11rvalue1 citylots.json
real	0m9.252s
user	0m8.852s
sys	0m0.376s
```

**Comment by kazuho** [comment]
Thank you for the PR!  Looks great.

**Pull request merged**
